micronaut:
  application:
    name: chat-application
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              refresh-token:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    enabled: true
    users:
      user:
        password: password
        roles: USER